In [1]:
import numpy as np

In [2]:
# creating an array from 1D list
list_1D = [0, 9, -3, 5, 4]
array_a = np.array(list_1D)
print(array_a)
print()

[ 0  9 -3  5  4]



In [3]:
# creating an array from 1D tupple
tuple_1D = (0, 9, -3, 5, 4)
array_b = np.array(tuple_1D)
print(array_b)
print()

[ 0  9 -3  5  4]



In [4]:
# soruces are not equal to each other
# but resulting array are
print(list_1D == tuple_1D)
print(array_a == array_b)
print((array_a == array_b).all())

False
[ True  True  True  True  True]
True


In [5]:
# basic info
print(array_a.shape)
print(array_a.ndim)
print(array_a.size)
print(array_a.dtype)

(5,)
1
5
int64


In [6]:
# creating an array from 2D list
list_2D = [[1, 2, 3], [4, 5, 6]]
matrix = np.array(list_2D)
print(matrix)
print()

[[1 2 3]
 [4 5 6]]



In [7]:
# basic info
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)

(2, 3)
2
6
int64


In [8]:
list_3D = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
]

tensor = np.array(list_3D)
print(tensor)
print()

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]



In [9]:
# basic info
print(tensor.shape)
print(tensor.ndim)
print(tensor.size)
print(tensor.dtype)

(3, 3, 3)
3
27
int64


In [10]:
# np.arange(start, end, step) creates an array of ints from start to end with step differece between each element
array = np.arange(3)
print(array)
print()
array = np.arange(3, 6)
print(array)
print()
array = np.arange(0, 9, 3)
print(array)
print()

[0 1 2]

[3 4 5]

[0 3 6]



In [11]:
# np.linspace(start, end, n) creates an array of n doubles from start to end
array = np.linspace(0, 10, 5)
print(array)
print()

[ 0.   2.5  5.   7.5 10. ]



In [12]:
# np.zeros(shape, dtype=float) creates an array of 0's stored as dtype of specified shape
array = np.zeros(5)
print(array)
print()

matrix = np.zeros((3, 2))
print(matrix)
print()

[0. 0. 0. 0. 0.]

[[0. 0.]
 [0. 0.]
 [0. 0.]]



In [13]:
# np.ones(shape, dtype=float) creates an array of 1's stored as dtype of specified shape
array = np.ones(5)
print(array)
print()

matrix = np.ones((3, 2))
print(matrix)
print()

[1. 1. 1. 1. 1.]

[[1. 1.]
 [1. 1.]
 [1. 1.]]



In [16]:
# np.full(n, a) creates an array with number a repeated n times
array = np.full(7, 2)
print(array)
print()

[2 2 2]



In [14]:
# np.eye(n, dtype=float) creates an identity matrix of size n x n
matrix = np.eye(3)
print(matrix)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [15]:
# np.random.rand(shape) creates an array of random numbers stored as floats of specified shape
array = np.random.rand(5)
print(array)
print()

matrix = np.random.rand(*(3, 2))
print(matrix)
print()

[0.85179443 0.65891453 0.98849468 0.59535658 0.97572327]

[[0.62555506 0.17981102]
 [0.73484057 0.84901349]
 [0.85113686 0.63310165]]

