In [1]:
import numpy as np

In [2]:
array = np.array([0, 1, 2, 3, 4, 5])
print(f"element at index 0 in array {array} is {array[0]}")
print(f"element at the last index in array {array} is {array[-1]}")
print(f"elements between indices 1 and 3 in array {array} are {array[1:4]}")

element at index 0 in array [0 1 2 3 4 5] is 0
element at the last index in array [0 1 2 3 4 5] is 5
elements between indices 1 and 3 in array [0 1 2 3 4 5] are [1 2 3]


In [3]:
# use append to add an element at the end of array
array = np.append(array, 6)
print(array)
print()

[0 1 2 3 4 5 6]



In [4]:
# use insert to insert an element at a given index
array = np.insert(array, 3, 8)
print(array)
print()

[0 1 2 8 3 4 5 6]



In [5]:
# modify a single element
array[2] = 7
print(array)
print()

[0 1 7 8 3 4 5 6]



In [6]:
# modify a number of consecutive elements
array[1:4] = [-1, -1, -1]
print(array)
print()

[ 0 -1 -1 -1  3  4  5  6]



In [7]:
# apply an operation to all the elements
array += 5
array //= 2
print(array)
print()

[2 2 2 2 4 4 5 5]



In [8]:
# apply a function to all elements
array = np.sqrt(array)
print(array)
print()

array = np.cos(array)
print(array)
print()

[1.41421356 1.41421356 1.41421356 1.41421356 2.         2.
 2.23606798 2.23606798]

[ 0.15594369  0.15594369  0.15594369  0.15594369 -0.41614684 -0.41614684
 -0.61727288 -0.61727288]



In [9]:
# remove an element
array = np.delete(array, (1, 3))
print(array)
print()

[ 0.15594369  0.15594369 -0.41614684 -0.41614684 -0.61727288 -0.61727288]

