In [1]:
import numpy as np

In [2]:
vector_row = np.array([[1, 2, 3, 4]])
print(vector_row)
print(vector_row.shape)
print()

[[1 2 3 4]]
(1, 4)



In [3]:
vector_column = np.array([[1], [2], [3], [4]])
print(vector_column)
print(vector_column.shape)
print()

[[1]
 [2]
 [3]
 [4]]
(4, 1)



In [4]:
vector_row_transposed = vector_row.T
print(vector_row_transposed)
print()

vector_column_transposed = vector_column.T
print(vector_column_transposed)
print()

[[1]
 [2]
 [3]
 [4]]

[[1 2 3 4]]



In [5]:
# norms
first_norm = np.linalg.norm(vector_row, 1)
print(first_norm)

second_norm = np.linalg.norm(vector_row, 2)
print(second_norm)

inf_norm = np.linalg.norm(vector_row, np.inf)
print(inf_norm)

4.0
5.477225575051661
10.0


In [6]:
# addition of vectors
vector_sum = vector_row + vector_row
print(vector_sum)
print()

scalar_sum = vector_row + 5
print(scalar_sum)
print()

[[2 4 6 8]]

[[6 7 8 9]]



In [7]:
# scalar multiplication
scalar_multiplication = 3 * vector_row
print(scalar_multiplication)
print()

[[ 3  6  9 12]]



In [8]:
# dot product
dot_product = np.dot(vector_row, vector_row.T)
print(dot_product)
print()

[[30]]



In [9]:
v = np.array([[9, 2, 5]])
w = np.array([[-3, 8, 2]])

In [10]:
# cross product
cross_product = np.cross(v, w)
print(cross_product)
print()

[[-36 -33  78]]



In [11]:
# the angle between two vectors
theta = np.arccos(np.dot(v, w.T) / (np.linalg.norm(v) * np.linalg.norm(w)))
print(theta)
print()

[[1.58166226]]

