In [1]:
import numpy as np

In [2]:
# addition, subtraction, multiplication, division by scalar
matrix = np.array([[3, 9], [21, -3]])

sum_result = matrix + 5
print(sum_result)
print()

diff_result = matrix - 1
print(diff_result)
print()

mult_result = matrix * 2
print(mult_result)
print()

div_result = matrix / 3
print(div_result)
print()

[[ 8 14]
 [26  2]]

[[ 2  8]
 [20 -4]]

[[ 6 18]
 [42 -6]]

[[ 1.  3.]
 [ 7. -1.]]



In [3]:
# addition, subtraction, multiplication, division by vector
vector = np.array([1, 2])

sum_result = matrix + vector
print(sum_result)
print()

diff_result = matrix - vector
print(diff_result)
print()

mult_result = matrix * vector
print(mult_result)
print()

div_result = matrix / vector
print(div_result)
print()

[[ 4 11]
 [22 -1]]

[[ 2  7]
 [20 -5]]

[[ 3 18]
 [21 -6]]

[[ 3.   4.5]
 [21.  -1.5]]



In [4]:
# addition, subtraction, multiplication, division by matrix
matrix_b = np.array([[4, 9], [25, 16]])

sum_result = matrix + matrix_b
print(sum_result)
print()

diff_result = matrix - matrix_b
print(diff_result)
print()

mult_result = matrix * matrix_b
print(mult_result)
print()

div_result = matrix_b / matrix
print(div_result)
print()

[[ 7 18]
 [46 13]]

[[ -1   0]
 [ -4 -19]]

[[ 12  81]
 [525 -48]]

[[ 1.33333333  1.        ]
 [ 1.19047619 -5.33333333]]



In [5]:
# transpose
transpose_a = np.transpose(matrix)
print(transpose_a)
print()

transpose_b = np.transpose(matrix_b)
print(transpose_b)
print()

[[ 3 21]
 [ 9 -3]]

[[ 4 25]
 [ 9 16]]



In [6]:
# determinant
determinant = np.linalg.det(matrix)
print(determinant)
print()

-198.0



In [7]:
# rank
rank = np.linalg.matrix_rank(matrix)
print(f"The rank of the matrix: {rank}")

The rank of the matrix: 2


In [8]:
# inverse
inverse = np.linalg.inv(matrix)
print("The inveres of the matrix")
print(inverse)
print()

product = np.dot(matrix, inverse)
print("The dot product of the matrix and its inverse.")
print(product.astype(int))
print()

The inveres of the matrix
[[ 0.01515152  0.04545455]
 [ 0.10606061 -0.01515152]]

The dot product of the matrix and its inverse.
[[1 0]
 [0 1]]



In [9]:
# sparsity
def count_sparsity(matrix):
    temp = np.nan_to_num(matrix, 0)
    sparsity = 1.0 - (np.count_nonzero(temp) / temp.size)
    return sparsity


matrix = np.array([[1, 1, 0, 1, 0, 0], [1, 0, 2, 0, 0, 1], [99, 0, 0, 2, 0, 0]])

sparsity = count_sparsity(matrix)
print(sparsity)

0.5555555555555556
