In [1]:
import numpy as np

In [2]:
matrix = np.array([[3, 9], [21, -3]])
print(matrix)
print()

[[ 3  9]
 [21 -3]]



In [3]:
reshaped_matrix = np.reshape(matrix, (4,))
print(reshaped_matrix)
print()

[ 3  9 21 -3]



In [4]:
reshaped_matrix = np.reshape(matrix, (1, 4))
print(reshaped_matrix)
print()

[[ 3  9 21 -3]]



In [5]:
reshaped_matrix = np.reshape(matrix, (4, 1))
print(reshaped_matrix)
print()

[[ 3]
 [ 9]
 [21]
 [-3]]



In [6]:
reshaped_matrix = np.reshape(matrix, (1, 4, 1))
print(reshaped_matrix)
print()

[[[ 3]
  [ 9]
  [21]
  [-3]]]



In [7]:
result = np.swapaxes(matrix, 0, 1)
print(result)
print()

[[ 3 21]
 [ 9 -3]]



In [8]:
result = np.swapaxes(matrix, 1, 0)
print(result)
print()

[[ 3 21]
 [ 9 -3]]



In [9]:
result = np.rollaxis(matrix, 0)
print(result)
print()

[[ 3  9]
 [21 -3]]



In [10]:
result = np.rollaxis(matrix, 1)
print(result)
print()

[[ 3 21]
 [ 9 -3]]



In [11]:
tensor = np.array([[[1, 0], [2, -1]], [[-3, 2], [7, 5]]])
print(tensor)
print()

[[[ 1  0]
  [ 2 -1]]

 [[-3  2]
  [ 7  5]]]



In [12]:
result = np.swapaxes(tensor, 0, 1)
print(result)
print()

[[[ 1  0]
  [-3  2]]

 [[ 2 -1]
  [ 7  5]]]



In [13]:
result = np.swapaxes(tensor, 0, 2)
print(result)
print()

[[[ 1 -3]
  [ 2  7]]

 [[ 0  2]
  [-1  5]]]



In [14]:
result = np.swapaxes(tensor, 1, 2)
print(result)
print()

[[[ 1  2]
  [ 0 -1]]

 [[-3  7]
  [ 2  5]]]



In [15]:
result = np.rollaxis(tensor, 1)
print(result)
print()

[[[ 1  0]
  [-3  2]]

 [[ 2 -1]
  [ 7  5]]]



In [16]:
result = np.rollaxis(tensor, 2)
print(result)
print()

[[[ 1  2]
  [-3  7]]

 [[ 0 -1]
  [ 2  5]]]



In [17]:
result = np.fliplr(matrix)
print(result)
print()

result = np.flipud(matrix)
print(result)
print()

[[ 9  3]
 [-3 21]]

[[21 -3]
 [ 3  9]]



In [18]:
result = np.roll(matrix, -1)
print(result)
print()

result = np.roll(matrix, 1)
print(result)
print()

[[ 9 21]
 [-3  3]]

[[-3  3]
 [ 9 21]]



In [19]:
result = np.rot90(matrix)
print(result)
print()

[[ 9 -3]
 [ 3 21]]

