In [1]:
import numpy as np

In [2]:
array = np.array([0, 1, 2, 3, 4, 5])

In [3]:
# find a key in an array
key = 2
condition = array == key
result = np.where(condition)
print(result)
print()

(array([2]),)



In [4]:
# max, min and their indices
print(array.max())
print()

print(array.min())
print()

indices = array.argmax()
print(indices)
print(array[indices])
print()

indices = array.argmin()
print(indices)
print(array[indices])
print()

5

0

5
5

0
0



In [5]:
condition = (array > 1) & (array < 4)
indices = np.where(condition)
print(indices)

(array([2, 3]),)


In [15]:
matrix = np.array([[0, 1], [9, 1], [5, 9]])

In [16]:
# find a key in a matrix
key = 1
condition = matrix == key
result = np.transpose(condition.nonzero())
print(result)
print()

[[0 1]
 [1 1]]



In [17]:
# max, min and their indices
print(matrix.max())
print()

print(matrix.min())
print()

indices = (matrix == matrix.max()).nonzero()
print(np.transpose(indices))
print(matrix[indices])
print()

indices = (matrix == matrix.min()).nonzero()
print(np.transpose(indices))
print(matrix[indices])
print()

9

0

[[1 0]
 [2 1]]
[9 9]

[[0 0]]
[0]



In [9]:
unique_values = np.unique(matrix)
print(unique_values)
print()

[0 1 5 9]



In [10]:
unique, freq = np.unique(matrix, return_counts=True)
histogram = dict(zip(unique, freq))
print(histogram)
print()

{0: 1, 1: 3, 5: 1, 9: 1}

