In [1]:
import numpy as np

In [2]:
array_a = np.array([0, 1, 2])
array_b = np.array([4, 5, 6])

In [3]:
result = np.concatenate((array_a, array_b))
print(result)
print()

[0 1 2 4 5 6]



In [4]:
result = np.vstack((array_a, array_b))
print(result)
print()

result = np.hstack((array_a, array_b))
print(result)
print()

[[0 1 2]
 [4 5 6]]

[0 1 2 4 5 6]



In [5]:
connected = np.concatenate((array_a, array_b))
result = np.split(connected, 3)

for array in result:
    print(array)
    print()

[0 1]

[2 4]

[5 6]



In [6]:
matrix_a = np.array([[0, 1], [2, 3]])
matrix_b = np.array([[4, 5], [6, 4]])

In [7]:
result = np.concatenate((matrix_a, matrix_b))
print(result)
print()

[[0 1]
 [2 3]
 [4 5]
 [6 4]]



In [8]:
result = np.vstack((matrix_a, matrix_b))
print(result)
print()

result = np.hstack((matrix_a, matrix_b))
print(result)
print()

[[0 1]
 [2 3]
 [4 5]
 [6 4]]

[[0 1 4 5]
 [2 3 6 4]]



In [9]:
connected = np.concatenate((matrix_a, matrix_b))
result = np.split(connected, 4)

for array in result:
    print(array)
    print()

[[0 1]]

[[2 3]]

[[4 5]]

[[6 4]]

