In [1]:
import numpy as np

In [2]:
array = np.random.rand(5)
print("Random floats between 0 and 1:")
print(array)

Random floats between 0 and 1:
[0.80432267 0.40333087 0.84736479 0.58867206 0.9747926 ]


In [3]:
array = np.random.rand(6, 3)
print("Random floats between 0 and 1:")
print("Array shape: 6,3")
print(array)

Random floats between 0 and 1:
Array shape: 6,3
[[0.86418048 0.96456329 0.05572784]
 [0.22103275 0.52069286 0.66488189]
 [0.31710385 0.70213041 0.01562073]
 [0.69482453 0.63363265 0.33663013]
 [0.37562011 0.7354865  0.1524171 ]
 [0.91927342 0.64574649 0.66919112]]


In [4]:
print("Single random int between 0 and 9:")
print(np.random.randint(10))

Single random int between 0 and 9:
1


In [5]:
array = np.random.randint(5, 25, size=(6, 3))
print("Random ints between 5 and 25:")
print("Array shape: 6,3")
print(array)

Random ints between 5 and 25:
Array shape: 6,3
[[23 18  8]
 [10 21 18]
 [ 9 12 18]
 [20 14 10]
 [ 5 11 14]
 [10 21 11]]


In [6]:
array = np.random.uniform(10)
print("Single float int between 0 and 9:")
print(array)

Single float int between 0 and 9:
4.5492127535630775


In [7]:
array = np.random.uniform(5, 25, size=(6, 3))
print("Random floats between 5 and 25:")
print("Array shape: 6,3")
print(array)

Random floats between 5 and 25:
Array shape: 6,3
[[12.4412726  24.32123325 19.38413227]
 [23.06782747 19.20185794 19.22057492]
 [21.60607994 14.51520617 14.32752104]
 [ 5.04144094 18.75984698 13.47717004]
 [22.94532892  5.75521177  5.09650704]
 [ 7.19522197 21.50436022 17.72969695]]
